import type { ResearchProduct } from "@/lib/types";

function links(keyword: string) {
  const encoded = encodeURIComponent(keyword);
  return {
    ebayListing: `https://www.ebay.com/sch/i.html?_nkw=${encoded}`,
    ebaySold: `https://www.ebay.com/sch/i.html?_nkw=${encoded}&LH_Sold=1&LH_Complete=1`,
    mercari: `https://jp.mercari.com/search?keyword=${encoded}`,
    yahooAuction: `https://auctions.yahoo.co.jp/search/search?p=${encoded}`,
    google: `https://www.google.com/search?q=${encoded}`,
  };
}

export const products: ResearchProduct[] = [
  {
    id: "good-001",
    seller: "good.japan398",
    sheetUrl: "https://docs.google.com/spreadsheets/d/1-fLyZj-FV52XnAOVBGWOrK3zPcWmz-3wSUr2elYZNrA",
    title: "Shimano Dendou Maru ED6000 Power Cable Electric Reel Saltwater Japan",
    brand: "Shimano",
    category: "電動リール電源コード",
    sold30: 22,
    productSoldCsv: 0,
    ebayPriceUsd: 79,
    shippingUsd: 0,
    totalUsd: 79,
    domesticPriceJpy: 7000,
    condition: "New",
    gapJpy: 2850,
    decision: "watch",
    reason: "送料予測込みで価格乖離50%未満。薄利注意",
    itemId: "178075473289",
    transportClass: "小型",
    shippingEstimateJpy: 2000,
    marketplaceLinks: links("Shimano Dendou Maru Power Cable"),
  },
  {
    id: "good-002",
    seller: "good.japan398",
    sheetUrl: "https://docs.google.com/spreadsheets/d/1-fLyZj-FV52XnAOVBGWOrK3zPcWmz-3wSUr2elYZNrA",
    title: "Daiwa SEABORG 300 Electric Reel Big Game Deep Sea 300 Fishing",
    brand: "Daiwa",
    category: "電動リール",
    sold30: 5,
    productSoldCsv: 0,
    ebayPriceUsd: 98,
    shippingUsd: 29.99,
    totalUsd: 127.99,
    domesticPriceJpy: 8500,
    condition: "Used",
    gapJpy: 6699,
    decision: "go",
    reason: "価格乖離50-100%。目視確認候補",
    itemId: "178164338978",
    transportClass: "中型",
    shippingEstimateJpy: 4000,
    marketplaceLinks: links("Daiwa SEABORG 300 Electric Reel"),
  },
  {
    id: "good-003",
    seller: "good.japan398",
    sheetUrl: "https://docs.google.com/spreadsheets/d/1-fLyZj-FV52XnAOVBGWOrK3zPcWmz-3wSUr2elYZNrA",
    title: "Shimano Dendou maru 1000H Electric Reel Big Game Saltwater Fishing",
    brand: "Shimano",
    category: "電動リール",
    sold30: 5,
    productSoldCsv: 0,
    ebayPriceUsd: 169,
    shippingUsd: 56,
    totalUsd: 225,
    domesticPriceJpy: 24000,
    condition: "Used",
    gapJpy: 5750,
    decision: "watch",
    reason: "送料予測込みで価格乖離50%未満。薄利注意",
    itemId: "177978798964",
    transportClass: "中型",
    shippingEstimateJpy: 4000,
    marketplaceLinks: links("Shimano Dendou maru 1000H Electric Reel"),
  },
  {
    id: "kakera-001",
    seller: "kakera",
    sheetUrl: "https://docs.google.com/spreadsheets/d/1BLncT5iIf_wXsfQOZCkV69eAfvJ4f1rX5VzD4JanlLM",
    title: "Kurouto Lures SU Monster Topwater Wake Bait 105mm 2oz Handcrafted",
    brand: "Kurouto Lures",
    category: "ルアー",
    sold30: 0,
    productSoldCsv: 0,
    ebayPriceUsd: 179,
    shippingUsd: 0,
    totalUsd: 179,
    domesticPriceJpy: 16500,
    condition: "New other",
    gapJpy: 8350,
    decision: "go",
    reason: "価格乖離50-100%。目視確認候補",
    itemId: "227287783287",
    transportClass: "小型",
    shippingEstimateJpy: 2000,
    marketplaceLinks: links("Kurouto Lures SU Monster Topwater"),
  },
  {
    id: "kakera-002",
    seller: "kakera",
    sheetUrl: "https://docs.google.com/spreadsheets/d/1BLncT5iIf_wXsfQOZCkV69eAfvJ4f1rX5VzD4JanlLM",
    title: "Kurouto Lures x SU Gillra140 Golden Shiner Swimbait Floating Handmade",
    brand: "Kurouto Lures",
    category: "ルアー",
    sold30: 0,
    productSoldCsv: 0,
    ebayPriceUsd: 179,
    shippingUsd: 0,
    totalUsd: 179,
    domesticPriceJpy: 16500,
    condition: "New other",
    gapJpy: 8350,
    decision: "go",
    reason: "価格乖離50-100%。目視確認候補",
    itemId: "227296971008",
    transportClass: "小型",
    shippingEstimateJpy: 2000,
    marketplaceLinks: links("Kurouto Lures Gillra140 Swimbait"),
  },
  {
    id: "shins-001",
    seller: "shins_reel_shop_kyoto",
    sheetUrl: "https://docs.google.com/spreadsheets/d/1WNAVEH_XlvO7kfU3Z4-1pXaqe5CefioFyF0poW8U9K0",
    title: "Shimano Electric Reel ForceMaster Fishing Reel From Japan",
    brand: "Shimano",
    category: "電動リール",
    sold30: 12,
    productSoldCsv: 2,
    ebayPriceUsd: 238,
    shippingUsd: 35,
    totalUsd: 273,
    domesticPriceJpy: 28000,
    condition: "Used",
    gapJpy: 9950,
    decision: "go",
    reason: "Sold数と価格乖離の両方が強い",
    itemId: "demo-shins-001",
    transportClass: "中型",
    shippingEstimateJpy: 4000,
    marketplaceLinks: links("Shimano ForceMaster Electric Reel"),
  },
  {
    id: "north-001",
    seller: "north834",
    sheetUrl: "https://docs.google.com/spreadsheets/d/1dpyRow8wYWKKXTc0C_-lgl5J9tcZnVC3TUNAS9UXds0",
    title: "Daiwa Tanacom Electric Reel Deep Sea Fishing Used Japan",
    brand: "Daiwa",
    category: "電動リール",
    sold30: 8,
    productSoldCsv: 1,
    ebayPriceUsd: 219,
    shippingUsd: 49,
    totalUsd: 268,
    domesticPriceJpy: 29000,
    condition: "Used",
    gapJpy: 7349,
    decision: "watch",
    reason: "価格差はあるが状態確認が必要",
    itemId: "demo-north-001",
    transportClass: "中型",
    shippingEstimateJpy: 4000,
    marketplaceLinks: links("Daiwa Tanacom Electric Reel"),
  },
  {
    id: "camera-001",
    seller: "kawamura-camera",
    sheetUrl: "https://docs.google.com/spreadsheets/d/15GWe55tBeWcZvWs9ackTyAJCCgOYOSh0cbid6rSqwds",
    title: "Nikon F3 Film Camera Body Black 35mm SLR From Japan",
    brand: "Nikon",
    category: "フィルムカメラ",
    sold30: 18,
    productSoldCsv: 4,
    ebayPriceUsd: 289,
    shippingUsd: 35,
    totalUsd: 324,
    domesticPriceJpy: 36000,
    condition: "Used",
    gapJpy: 12600,
    decision: "go",
    reason: "Sold数が多く価格乖離も十分",
    itemId: "demo-camera-001",
    transportClass: "中型",
    shippingEstimateJpy: 3500,
    marketplaceLinks: links("Nikon F3 Film Camera Body"),
  },
];
